// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCEmFNOHXwOMfTaTOG_XxZBT0PQpOB_do',
    appId: '1:624279043141:web:e389c60b7e70bd6660b72c',
    messagingSenderId: '624279043141',
    projectId: 'sbg-electric',
    authDomain: 'sbg-electric.firebaseapp.com',
    storageBucket: 'sbg-electric.appspot.com',
    measurementId: 'G-M84K12VDGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArOsHMG8cZj7aZ9a95fUY1gro_kChQJHU',
    appId: '1:624279043141:android:65312f5b4835514d60b72c',
    messagingSenderId: '624279043141',
    projectId: 'sbg-electric',
    storageBucket: 'sbg-electric.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwGyv1dpNVQrwWw5DaXJJ39G_zkyc-90U',
    appId: '1:624279043141:ios:73b15b9ba4a8759460b72c',
    messagingSenderId: '624279043141',
    projectId: 'sbg-electric',
    storageBucket: 'sbg-electric.appspot.com',
    iosClientId: '624279043141-c7quqttgh5ujm3u3b9g4qtnamtqg5vii.apps.googleusercontent.com',
    iosBundleId: 'mn.sbg.sbgelectric',
  );
}
